
CREATE TABLE country (
  id INT AUTO_INCREMENT PRIMARY KEY,
  iso_code CHAR(2) UNIQUE NOT NULL,
  name_local VARCHAR(191) NOT NULL,
  name_en VARCHAR(191) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
